/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { streamMaterial } from "../utils/streamMaterial"

export function Arena(props) {
  const group = useRef()
  const { nodes } = useGLTF("/arena2.glb")

  const clubMat = nodes.structure.material
  const sc = 10

  clubMat.map.repeat.set(sc, sc)
  clubMat.roughnessMap.repeat.set(sc, sc)
  clubMat.roughness = 1
  clubMat.metalness = 0
  clubMat.normalMap.repeat.set(sc, sc)
  clubMat.metalnessMap.repeat.set(sc, sc)

  return (
    <group ref={group} {...props} dispose={null} scale={50}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.structure.geometry}
        material={nodes.structure.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen9.geometry}
        material={nodes.screen9.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen4.geometry}
        material={nodes.screen4.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen5.geometry}
        material={nodes.screen5.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen6.geometry}
        material={nodes.screen6.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen10.geometry}
        material={nodes.screen10.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen7.geometry}
        material={nodes.screen7.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen0.geometry}
        material={nodes.screen0.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen8.geometry}
        material={nodes.screen8.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen1.geometry}
        material={nodes.screen1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen2.geometry}
        material={nodes.screen2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen3.geometry}
        material={nodes.screen3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen11.geometry}
        material={nodes.screen11.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen12.geometry}
        material={nodes.screen12.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen13.geometry}
        material={nodes.screen13.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen18.geometry}
        material={nodes.screen18.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen17.geometry}
        material={nodes.screen17.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen16.geometry}
        material={nodes.screen16.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen14.geometry}
        material={nodes.screen14.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen15.geometry}
        material={nodes.screen15.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.widescreen0.geometry}
        material={streamMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.widescreen1.geometry}
        material={streamMaterial}
      />
    </group>
  )
}

useGLTF.preload("/arena2.glb")
