/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ShapeOne(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/swirl.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sprangle.geometry}
        material={materials.phong1SG}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[10, 10, 10]}
      />
    </group>
  )
}

useGLTF.preload('/swirl.gltf')
